FROM node:20-alpine AS builder
WORKDIR /tmi
COPY package*.json ./
RUN npm install
COPY . .

ARG NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL

RUN npm run build

FROM node:20-alpine
WORKDIR /tmi
COPY --from=builder /tmi/.next/standalone ./
COPY --from=builder /tmi/.next/static ./.next/static
COPY --from=builder /tmi/public ./public
CMD ["node", "server.js"]