FROM gradle:8.14-jdk17 AS build
WORKDIR /tmi

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

RUN chmod +x ./gradlew

COPY src src

RUN ./gradlew clean build -x test --no-daemon


FROM eclipse-temurin:17-jre-jammy
WORKDIR /tmi
COPY --from=build /tmi/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]