CREATE DATABASE IF NOT EXISTS tmidb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE tmidb;

CREATE TABLE IF NOT EXISTS tmi (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
